import type { Metadata } from "next";

import { Header } from "@/modules/shared/components/layout/header";
import { Category } from "@/modules/core/types";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetch("https://fakestoreapi.com/products/categories");
  const categories: Category[] = await data.json();

  return (
    <html lang="en">
      <body className="">
        <Header categories={categories} />
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js" />
      </body>
    </html>
  );
}
