import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import { Header } from "@/modules/shared/components/layout/header";
import { Category } from "@/modules/core/types";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetch("https://fakestoreapi.com/products/categories");
  const categories: Category[] = await data.json();

  return (
    <html lang="en">
      <UserProvider>
        <body
          className=""
        >
          <Header categories={categories} />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
